# Generated by Django 5.0.2 on 2024-02-16 10:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SwadeshChat', '0004_membertype_group_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group_member',
            new_name='GroupMember',
        ),
    ]
